program:
  linpeas:
    url: https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
    type: script
    os: linux
  winpeas:
    url: https://raw.githubusercontent.com/carlospolop/PEASS-ng/master/winPEAS/winPEASexe/binaries/Obfuscated%20Releases/winPEASany.exe
    type: binary
    os: windows
  sharphound:
    url: https://raw.githubusercontent.com/BloodHoundAD/BloodHound/master/Collectors/SharpHound.ps1
    type: script
    os: windows
  powerview:
    url: https://raw.githubusercontent.com/PowerShellEmpire/PowerTools/master/PowerView/powerview.ps1
    type: script
    os: windows
  nc:
    url: https://raw.githubusercontent.com/yunchih/static-binaries/master/nc
    type: binary
    os: linux
  wget:
    url: https://raw.githubusercontent.com/yunchih/static-binaries/master/wget
    type: binary
    os: linux
  tcpdump:
    url: https://raw.githubusercontent.com/yunchih/static-binaries/master/tcpdump
    type: binary
    os: linux
  chisel:
    url: https://raw.githubusercontent.com/LuskaBol/static-binaries/main/chisel
    type: binary
    os: linux
  docker:
    url: https://raw.githubusercontent.com/LuskaBol/static-binaries/main/docker
    type: binary
    os: linux
  nc.exe:
    url: https://raw.githubusercontent.com/int0x33/nc.exe/master/nc.exe
    type: binary
    os: windows
  nmap:
    url: https://raw.githubusercontent.com/andrew-d/static-binaries/master/binaries/linux/x86_64/nmap
    type: binary
    os: linux
  mimikatz:
    url: https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/master/Exfiltration/Invoke-Mimikatz.ps1
    type: script
    os: windows
  mimikatz.exe:
    url: https://raw.githubusercontent.com/ParrotSec/mimikatz/master/x64/mimikatz.exe
    type: binary
    os: windows
