colors = ['red',
    'yellow',
    'green',
    'cyan',
    'blue',
    'magenta',
]
fonts = ['smslant',
    'crawford',
    'cursive',
    'pyramid',
    'stacey',
    'slant',
    '5lineoblique',
    'ticks',
    'contessa',
    'hex',
    'pawp',
    'block',
    'graffiti',
    'linux',
    'charact3',
    'bulbhead',
]
